upgrade to summary model and various bug fixes

diff --git a/modules/summary/inference/helm_chart/templates/deployment.yaml b/modules/summary/inference/helm_chart/templates/deployment.yaml
--- a/modules/summary/inference/helm_chart/templates/deployment.yaml
+++ b/modules/summary/inference/helm_chart/templates/deployment.yaml
@@ -6,7 +6,7 @@ metadata:
   labels:
     app: {{ .Values.service.name }}
 spec:
-  replicas: {{ .Values.replicas }}
+  replicas: {{ .Values.replicas.min }}
   selector:
     matchLabels:
       app: {{ .Values.service.name }}
@@ -17,19 +17,21 @@ spec:
     spec:
       nodeSelector:
         node: "{{ .Values.nodeSelector.node }}"
-      runtimeClassName: nvidia
       tolerations:
         - key: "node"
           value: "{{ .Values.nodeSelector.node }}"
           effect: "NoSchedule"
       initContainers:
+        {{- if .Values.waitForDependencies }}
         - name: wait-for-cache
-          image: public.ecr.aws/c9r4x6y5/eyelevel/busybox:latest
-          imagePullPolicy: "Always"
+          image: {{ .Values.busybox.repository }}:{{ .Values.busybox.tag }}
+          imagePullPolicy: "{{ .Values.busybox.pull }}"
           command: ['sh', '-c', "until nc -z {{ .Values.dependencies.cache }}; do echo waiting for cache; sleep 2; done"]
+        {{- end }}
+        {{- if .Values.createSymlink }}
         - name: create-symlink
-          image: public.ecr.aws/c9r4x6y5/eyelevel/busybox:latest
-          imagePullPolicy: "Always"
+          image: {{ .Values.busybox.repository }}:{{ .Values.busybox.tag }}
+          imagePullPolicy: "{{ .Values.busybox.pull }}"
           command: ["/bin/sh", "-c", "--"]
           args: ["echo 'Running ldconfig_symlink.sh on this node'; /scripts/ldconfig_symlink.sh"]
           securityContext:
@@ -50,9 +52,75 @@ spec:
               mountPath: /host-bin
             - name: host-usr-bin
               mountPath: /host-usr-bin
+        {{- end }}
+        - name: update-permissions
+          image: {{ .Values.busybox.repository }}:{{ .Values.busybox.tag }}
+          imagePullPolicy: "{{ .Values.busybox.pull }}"
+          command:
+            - /bin/sh
+            - -c
+            - |
+              chown -R {{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.runAsGroup }} /workspace/hf_models_cache && chmod -R 777 /workspace/hf_models_cache
+          securityContext:
+            privileged: true
+          volumeMounts:
+            - name: model-volume
+              mountPath: /workspace/hf_models_cache
+        - name: download-model
+          image: {{ .Values.busybox.repository }}:{{ .Values.busybox.tag }}
+          imagePullPolicy: "{{ .Values.busybox.pull }}"
+          command:
+            - /bin/sh
+            - -c
+            - |
+              download_and_extract_model() {
+                echo "Model downloading started..."
+
+                touch /workspace/hf_models_cache/downloading
+
+                echo "00 01 02 03 04" | tr ' ' '\n' | xargs -n 1 -P 5 -I {} sh -c \
+                  'MAX_RETRIES=3; RETRIES=0; SUCCESS=0; PART={}; URL=https://upload.groundx.ai/summary/model/current/model.tar.gz.part.$PART; \
+                  while [ $RETRIES -lt $MAX_RETRIES ]; do \
+                    echo "Download [attempt $RETRIES] summary.tar.gz.part.$PART"; \
+                    wget -q -O /workspace/hf_models_cache/summary.tar.gz.part.$PART $URL && { echo "Downloaded summary.tar.gz.part.$PART successfully."; SUCCESS=1; break; }; \
+                    echo "Failed to download $URL. Retrying..."; RETRIES=$((RETRIES + 1)); sleep 3; \
+                  done; \
+                  [ $SUCCESS -eq 0 ] && { echo "Failed to download $URL after $MAX_RETRIES attempts. Exiting."; rm /workspace/hf_models_cache/downloading; exit 1; }; \
+                  echo "Unzipping summary.tar.gz.part.$PART..."; tar -xzf /workspace/hf_models_cache/summary.tar.gz.part.$PART -C /workspace/hf_models_cache/; echo "Unzipping summary.tar.gz.part.$PART complete...";'
+
+                rm /workspace/hf_models_cache/summary.tar.*
+                rm /workspace/hf_models_cache/downloading
+                touch /workspace/hf_models_cache/complete
+              }
+              if [ ! -f /workspace/hf_models_cache/complete ]; then
+                if [ ! -f /workspace/hf_models_cache/downloading ]; then
+                  download_and_extract_model
+                else
+                  echo "Download in progress by another pod. Waiting..."
+                  while [ -f /workspace/hf_models_cache/downloading ] || [ ! -f /workspace/hf_models_cache/complete ]; do
+                    sleep $((3 + RANDOM % 2))
+                  done
+
+                  if [ ! -f /workspace/hf_models_cache/complete ]; then
+                    download_and_extract_model
+                  else
+                    echo "Model cache ready."
+                  fi
+                fi
+              else
+                echo "Model cache already exists. Skipping download."
+              fi
+
+              echo "Model load done."
+          securityContext:
+            runAsUser: {{ .Values.securityContext.runAsUser }}
+            runAsGroup: {{ .Values.securityContext.runAsGroup }}
+          volumeMounts:
+            - name: model-volume
+              mountPath: /workspace/hf_models_cache
       containers:
         - name: {{ .Values.service.name }}
-          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
+          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
           imagePullPolicy: "{{ .Values.image.pull }}"
           env:
             - name: POD_NAME
@@ -60,42 +128,35 @@ spec:
                 fieldRef:
                   fieldPath: metadata.name
           workingDir: /workspace
-          # LOAD_MODEL=yes && LOCAL=0 && export PYTHONPATH=/workspace && celery -A summary.celery.appSummary worker -n summary-w1 --loglevel=INFO --concurrency=1 --queues=summary_inference_queue
           command:
             - /bin/bash
             - -c
-            #- |
-            #  export PYTHONPATH=/workspace && tar -xzf /workspace/hf_models_cache.summary.tar.gz -C /workspace && rm /workspace/hf_models_cache.summary.tar.gz && while true; do sleep 30; done
             - |
-              export PYTHONPATH=/workspace && tar -xzf /workspace/hf_models_cache.summary.tar.gz -C /workspace && rm /workspace/hf_models_cache.summary.tar.gz && supervisord -c /workspace/supervisord.conf
+              export PYTHONPATH=/workspace:/workspace/vllm:$PYTHONPATH && supervisord -c /workspace/supervisord.conf
           securityContext:
             runAsUser: {{ .Values.securityContext.runAsUser }}
+            runAsGroup: {{ .Values.securityContext.runAsGroup }}
           livenessProbe:
-            exec:
-              command:
-                - /bin/sh
-                - -c
-                - ps aux | grep 'summary.celery.appSummary' | grep -v grep || exit 1
+            httpGet:
+              path: /alive
+              port: 8080
             initialDelaySeconds: 30
-            failureThreshold: 10
-            periodSeconds: 30
+            failureThreshold: 8
+            periodSeconds: 15
           readinessProbe:
-            exec:
-              command:
-                - /bin/sh
-                - -c
-                - ps aux | grep 'summary.celery.appSummary' | grep -v grep || exit 1
-            initialDelaySeconds: 30
-            periodSeconds: 60
+            httpGet:
+              path: /health
+              port: 8080
+            initialDelaySeconds: 180
+            failureThreshold: 20
+            periodSeconds: 15
           resources:
             limits:
               cpu: "{{ .Values.resources.limits.cpu }}"
               memory: "{{ .Values.resources.limits.memory }}"
-              nvidia.com/gpu: {{ .Values.resources.limits.gpu }}
             requests:
               cpu: "{{ .Values.resources.requests.cpu }}"
               memory: "{{ .Values.resources.requests.memory }}"
-              nvidia.com/gpu: {{ .Values.resources.requests.gpu }}
           volumeMounts:
             - name: config-models
               mountPath: /workspace/config_models.py
@@ -106,6 +167,8 @@ spec:
             - name: supervisord-volume
               mountPath: /workspace/supervisord.conf
               subPath: supervisord.conf
+            - name: model-volume
+              mountPath: /workspace/hf_models_cache
       volumes:
         - name: config-models
           configMap:
@@ -116,10 +179,12 @@ spec:
         - name: supervisord-volume
           configMap:
             name: summary-supervisord-24gb-conf-map
+        {{- if .Values.createSymlink }}
         - name: {{ .Values.service.name }}
           configMap:
             name: ldconfig-symlink-map
             defaultMode: 0555
+        {{- end }}
         - name: host-sbin
           hostPath:
             path: /sbin
@@ -136,3 +201,6 @@ spec:
           hostPath:
             path: /usr/bin
             type: Directory
+        - name: model-volume
+          persistentVolumeClaim:
+            claimName: {{ .Values.pv.name }}
